spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mysql://mysql:3306/newstar?serverTimezone=Asia/Seoul
    username: ${MYSQL_USER_ID}
    password: ${MYSQL_USER_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
