spring:
  config:
    activate:
      on-profile: create
  
  datasource:
    url: jdbc:mysql://mysql:3306/newstar?serverTimezone=Asia/Seoul
    username: ${MYSQL_USER_PROD_ID}
    password: ${MYSQL_USER_PROD_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: create
