dev:
  DB:
    user: "newstar"
    password: "newstar"
    host: "localhost"
    port: 3306
    database: "newstar"
  ES:
    host: "localhost:9200"

prod:
  DB:
    user: "newstar"
    password: "newstar!!"
    host: "mysql"
    port: 3306
    database: "newstar"
  ES:
    host: "elastic:9200"
